// pages/privacy-policy.tsx
import React from 'react'
import { motion } from 'framer-motion'

const PrivacyPolicy = () => {
  return (
    <div className="text-white">
      <main className="mx-auto md:px-4 pt-12 max-w-7xl md:mt-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="rounded-2xl pt-8"
        >
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-gray-400">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="prose prose-invert max-w-none">
            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
              <p className="text-gray-300 mb-4">
                Welcome to ArtifyAI. We are committed to protecting your personal information and your right to privacy. 
                This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our service.
              </p>
              <p className="text-gray-300">
                If you have any questions or concerns about this privacy notice, or our practices with regards to your personal 
                information, please contact us at privacy@artifyai.com.
              </p>
            </section>

            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">2. Information We Collect</h2>
              <h3 className="text-xl font-medium mb-2">Personal Information</h3>
              <p className="text-gray-300 mb-4">
                We collect personal information that you voluntarily provide to us when you register on the service, 
                express an interest in obtaining information about us or our products and services, or otherwise when you contact us.
              </p>
              <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
                <li>Wallet addresses and blockchain transaction data</li>
                <li>Contact information (email address)</li>
                <li>Artwork images and metadata you upload</li>
                <li>Authentication reports generated by our AI</li>
              </ul>

              <h3 className="text-xl font-medium mb-2">Automatically Collected Information</h3>
              <p className="text-gray-300">
                We automatically collect certain information when you visit, use, or navigate the service. This information does not 
                reveal your specific identity but may include device and usage information.
              </p>
            </section>

            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">3. How We Use Your Information</h2>
              <p className="text-gray-300 mb-4">
                We use personal information collected via our service for a variety of business purposes described below:
              </p>
              <ul className="list-disc list-inside text-gray-300 space-y-2">
                <li>To facilitate account creation and authentication</li>
                <li>To provide and maintain our service</li>
                <li>To process your transactions and mint NFTs</li>
                <li>To analyze artwork using our AI algorithms</li>
                <li>To communicate with you about updates or security alerts</li>
                <li>To enforce our terms, conditions, and policies</li>
              </ul>
            </section>

            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">4. Data Security</h2>
              <p className="text-gray-300">
                We have implemented appropriate technical and organizational security measures designed to protect the security of any 
                personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure.
              </p>
            </section>

            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">5. Your Privacy Rights</h2>
              <p className="text-gray-300 mb-4">
                Depending on your location, you may have the following rights regarding your personal information:
              </p>
              <ul className="list-disc list-inside text-gray-300 space-y-2">
                <li>The right to access and receive a copy of your personal information</li>
                <li>The right to request correction of any inaccurate personal information</li>
                <li>The right to request deletion of your personal information</li>
                <li>The right to withdraw your consent at any time where we relied on your consent to process your personal information</li>
              </ul>
            </section>

            <section className="mb-8 bg-gray-900 p-5 sm:p-8 rounded-lg">
              <h2 className="text-2xl font-semibold mb-4">6. Contact Us</h2>
              <p className="text-gray-300">
                If you have questions or comments about this policy, you may email us at privacy@artifyai.com or by post to:
              </p>
              <p className="text-gray-300 mt-2">
                ArtifyAI Inc.<br />
                123 Blockchain Avenue<br />
                San Francisco, CA 94103<br />
                United States
              </p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  )
}

export default PrivacyPolicy
